### PR TITLE
Improve/menu

### PR DESCRIPTION
**Pull request by yorkie**
Set the label from `arguments[0]` if the `template.label` doesn't get set by caller, this could make compatible with the following call:

```js
Editor.MainMenu.add('File/Save', { 'message': 'channel' })
```

@jwu I'm quite not sure if this is a real correct patch because it breaks the SRP. In the other hand, it actually makes sense to help developer to fix some of mistakes in this API.

### CODE REVIEW

**Comment by jwu** [comment]
This is a good advice. But I saw it only in Editor.MainMenu. Why not move the code to EditorMenu.prototype.add instead? 

By the way, you should check if the template is an array. The template accept array or object, and the call should works only for object type.

**Comment by yorkie** [comment]
Hi @jwu Do you think this framework should throw an error when there is some template item has no `label` in array mode? Or warning? 

Because when I was working on code-editor and got an empty label without any hints about that.

**Comment by jwu** [comment]
Just use `Editor.warn( 'xyz' );` during parseTemplate. I agree we should warn user about this.

**Comment by yorkie** [comment]
Got it, doing...

**Comment by yorkie** [comment]
Done @jwu :)

**Pull request merged**
